/*********************************************************************
*
* PROGRAM NAME          : COPYINVHISTORY.SQL
*
*
* DESCRIPTION           : THIS PL/SQL SCRIPT COPIES THE RECORDS
*
*                         FROM           TO (OWNED BY BATCH_MAXIMO)
*                         -----          --------------------------
*                         INVENTORY      LBL_INVENTORY_HIST
*                         INVBALANCES    LBL_INVBALANCES_HIST
*                         INVCOST        LBL_INVCOST_HIST
*
*                         IT SETS THE VALUE OF MTHENDDATE COLUMN TO THE
*                         LAST DAY OF THE ACCOUNTING PERIOD
*
*
* AUTHOR                : PANKAJ BHIDE
*
* DATE WRITTEN          : 24-MAR-2009
*
* DATE MODIFIED         :
*
* MODIFICATION HISTORTY :
*********************************************************************/
WHENEVER SQLERROR EXIT 1 ROLLBACK;

SET HEADING OFF
SET ECHO OFF
SET TERMOUT OFF
SET SERVEROUTPUT ON

DECLARE

     REC_CNT_T           NUMBER(7) :=0;
     TRANSACTION_DT_T    INVOICE.STATUSDATE%TYPE;
     MESSAGE_T           VARCHAR2(2000);
     ORGID_T             FINANCIALPERIODS.ORGID%TYPE;
     SITEID_T            INVENTORY.SITEID%TYPE;

/*********************************************************************
 MAIN PROGRAM STARTS FROM HERE
*********************************************************************/
BEGIN

 ORGID_T   :=UPPER('&1');
 SITEID_T  :=UPPER('&2');

 IF (ORGID_T IS NULL OR LENGTH(ORGID_T)=0) THEN
    ORGID_T :='LBNL';
 END IF;

 IF (SITEID_T IS NULL OR LENGTH(SITEID_T)=0) THEN
     SITEID_T :='FAC';
 END IF;

SELECT 'COPYING THE INVENTORY RECORDS BEGAN AT '||
     TO_CHAR(SYSDATE,'MM/DD/YY HH24:MI:SS') INTO MESSAGE_T
FROM SYS.DUAL;

DBMS_OUTPUT.PUT_LINE(MESSAGE_T);

SELECT 'COUNT OF RECORDS IN LBL_INVBALANCES_HIST BEFORE LOADING: ' || LTRIM(TO_CHAR(COUNT(*)))
INTO MESSAGE_T
FROM  BATCH_MAXIMO.LBL_INVBALANCES_HIST
WHERE ORGID=ORGID_T
AND   SITEID=SITEID_T;

DBMS_OUTPUT.PUT_LINE(MESSAGE_T);

SELECT 'COUNT OF RECORDS IN LBL_INVENTORY_HIST BEFORE LOADING: ' || LTRIM(TO_CHAR(COUNT(*)))
INTO MESSAGE_T
FROM BATCH_MAXIMO.LBL_INVENTORY_HIST
WHERE ORGID=ORGID_T
AND   SITEID=SITEID_T;

DBMS_OUTPUT.PUT_LINE(MESSAGE_T);

SELECT 'COUNT OF RECORDS IN LBL_INVCOST_HIST BEFORE LOADING: ' || LTRIM(TO_CHAR(COUNT(*)))
INTO MESSAGE_T
FROM BATCH_MAXIMO.LBL_INVCOST_HIST
WHERE ORGID=ORGID_T
AND   SITEID=SITEID_T;

DBMS_OUTPUT.PUT_LINE(MESSAGE_T);


-- GET THE LAST DATE OF THE FINANCIALPERIOD
-- FOR WHICH THE STG FEEDER FILE IS BEING SENT TO FMS

SELECT TRUNC((PERIODEND-1))
INTO TRANSACTION_DT_T
FROM FINANCIALPERIODS
WHERE FINANCIALPERIOD=(SELECT MIN(FINANCIALPERIOD)
FROM FINANCIALPERIODS WHERE
NVL(CLOSEDBY,' ') NOT LIKE '%STG%'
AND ORGID=ORGID_T)
AND ORGID=ORGID_T;


REC_CNT_T :=0;

SELECT COUNT(*) INTO REC_CNT_T
FROM BATCH_MAXIMO.LBL_INVBALANCES_HIST A,
     BATCH_MAXIMO.LBL_INVENTORY_HIST B
WHERE  A.ITEMNUM=B.ITEMNUM
AND    A.LOCATION=B.LOCATION
AND    A.BINNUM=B.BINNUM
AND    A.MTHENDDATE=B.MTHENDDATE
AND    A.ORGID=B.ORGID
AND    A.SITEID=B.SITEID
AND    A.MTHENDDATE=TRANSACTION_DT_T
AND    A.ORGID=ORGID_T
AND    A.SITEID=SITEID_T;

IF REC_CNT_T = 0 THEN

   -- START COPYING THE RECORDS FROM INVBALANCES TO LBL_INVBALANCES_HIST
   INSERT INTO BATCH_MAXIMO.LBL_INVBALANCES_HIST
   (ITEMNUM, LOCATION, BINNUM,LOTNUM,CURBAL,PHYSCNT,PHYSCNTDATE,
    RECONCILED,SOURCESYSID,OWNERSYSID,EXTERNALREFID,APISEQ,SENDERSYSID,
    ORGID,SITEID, ROWSTAMP,CONDITIONCODE,INVBALANCESID, ITEMSETID,
    MTHENDDATE)
   SELECT ITEMNUM, LOCATION, BINNUM,LOTNUM,CURBAL,PHYSCNT,PHYSCNTDATE,
    RECONCILED,SOURCESYSID,OWNERSYSID,EXTERNALREFID,APISEQ,SENDERSYSID,
    ORGID,SITEID, ROWSTAMP,CONDITIONCODE,INVBALANCESID, ITEMSETID,
    TRANSACTION_DT_T FROM MAXIMO.INVBALANCES WHERE ORGID=ORGID_T
    AND SITEID=SITEID_T;


 -- START COPYING THE RECORDS FROM INVENTORY TO LBL_INVENTORY_HIST
   INSERT INTO BATCH_MAXIMO.LBL_INVENTORY_HIST(ITEMNUM, LOCATION,BINNUM,VENDOR,
    MANUFACTURER,MODELNUM,CATALOGCODE,MINLEVEL,MAXLEVEL,
    CATEGORY,ORDERUNIT,ISSUEUNIT,ORDERQTY ,LASTISSUEDATE,
    ISSUEYTD,ISSUE1YRAGO,ISSUE2YRAGO,ISSUE3YRAGO,
    ABCTYPE,CCF,SSTOCK,DELIVERYTIME,
    IL1,IL2,IL3,IL4,
    IL5,IL6,IL7,
    GLACCOUNT,CONTROLACC,SHRINKAGEACC,INVCOSTADJACC,
    SOURCESYSID,OWNERSYSID,EXTERNALREFID,APISEQ,SENDERSYSID,
    ORGID,SITEID,INTERNAL,INVENTORYID,ITEMSETID,
    STORELOC,STORELOCSITEID,ROWSTAMP,
    MTHENDDATE)
    SELECT
    ITEMNUM, LOCATION,BINNUM,VENDOR,
    MANUFACTURER,MODELNUM,CATALOGCODE,MINLEVEL,MAXLEVEL,
    CATEGORY,ORDERUNIT,ISSUEUNIT,ORDERQTY ,LASTISSUEDATE,
    ISSUEYTD,ISSUE1YRAGO,ISSUE2YRAGO,ISSUE3YRAGO,
    ABCTYPE,CCF,SSTOCK,DELIVERYTIME,
    IL1,IL2,IL3,IL4,
    IL5,IL6,IL7,
    GLACCOUNT,CONTROLACC,SHRINKAGEACC,INVCOSTADJACC,
    SOURCESYSID,OWNERSYSID,EXTERNALREFID,APISEQ,SENDERSYSID,
    ORGID,SITEID,INTERNAL,INVENTORYID,ITEMSETID,
    STORELOC,STORELOCSITEID,ROWSTAMP,TRANSACTION_DT_T
    FROM MAXIMO.INVENTORY WHERE ORGID=ORGID_T
    AND SITEID=SITEID_T;


    INSERT INTO BATCH_MAXIMO.LBL_INVCOST_HIST
    (AVGCOST,CONDITIONCODE,CONDRATE,CONTROLACC,GLACCOUNT,INVCOSTADJACC,
    INVCOSTID,ITEMNUM,ITEMSETID,LASTCOST,LOCATION,ORGID,SHRINKAGEACC,
    SITEID,STDCOST,ROWSTAMP,MTHENDDATE)
    SELECT AVGCOST,CONDITIONCODE,CONDRATE,CONTROLACC,GLACCOUNT,INVCOSTADJACC,
    INVCOSTID,ITEMNUM,ITEMSETID,LASTCOST,LOCATION,ORGID,SHRINKAGEACC,
    SITEID,STDCOST,ROWSTAMP,TRANSACTION_DT_T
    FROM MAXIMO.INVCOST WHERE ORGID=ORGID_T AND SITEID=SITEID_T;


 END IF;  -- REC_CNT_T !=0


SELECT 'COUNT OF RECORDS IN LBL_INVBALANCES_HIST AFTER LOADING: ' || LTRIM(TO_CHAR(COUNT(*)))
INTO MESSAGE_T
FROM BATCH_MAXIMO.LBL_INVBALANCES_HIST
WHERE ORGID=ORGID_T
AND   SITEID=SITEID_T;

DBMS_OUTPUT.PUT_LINE(MESSAGE_T);

SELECT 'COUNT OF RECORDS IN LBL_INVENTORY_HIST AFTER  LOADING: ' || LTRIM(TO_CHAR(COUNT(*)))
INTO MESSAGE_T
FROM BATCH_MAXIMO.LBL_INVENTORY_HIST
WHERE ORGID=ORGID_T
AND   SITEID=SITEID_T;

DBMS_OUTPUT.PUT_LINE(MESSAGE_T);

SELECT 'COUNT OF RECORDS IN LBL_INVCOST_HIST AFTER LOADING: ' || LTRIM(TO_CHAR(COUNT(*)))
INTO MESSAGE_T
FROM BATCH_MAXIMO.LBL_INVCOST_HIST
WHERE ORGID=ORGID_T
AND   SITEID=SITEID_T;

DBMS_OUTPUT.PUT_LINE(MESSAGE_T);



SELECT 'COPYING THE INVENTORY RECORDS ENDED AT '||
     TO_CHAR(SYSDATE,'MM/DD/YY HH24:MI:SS') INTO MESSAGE_T
FROM SYS.DUAL;

 COMMIT;


END;

/

