REM **************************************************************************
REM
REM PROGRAM NAME : FLEET_FEEDER_MTH04.SQL
REM
REM PURPOSE      : TO OBTAIN NUMBER OF RECORDS WRITTEN TO
REM                INVOICE  TABLE FOR THE GIVEN MONTH
REM
REM DATE         : 01/24/01
REM
REM AUTHOR       : PANKAJ BHIDE
REM
REM MODIFICIATION
REM     HISTORY  : 12/13/02 PANKAJ - MODIFIED TO TAKE CARE OF THE
REM                         ACCELERATED GL CLOSE.
REM
REM **************************************************************************
SET HEADING OFF
SET FEEDBACK OFF
SET TERMOUT OFF
SET ECHO OFF
SET PAGESIZE 0
SET SPACES 0
SET NEWPAGE 0
SET LINESIZE 6
SET VERIFY OFF

SPOOL fl_cnt

SELECT RTRIM(LTRIM(TO_CHAR(COUNT(*),'999999')))
FROM MAXIMO.INVOICE
WHERE  ORGID='&1'
AND    SITEID='&2'
AND    INVOICENUM LIKE 'FLEET%'
AND TRUNC(INVOICEDATE) =(SELECT TRUNC(X.PERIODEND-1)
FROM   FINANCIALPERIODS X
WHERE  X.ORGID='&1' AND X.FINANCIALPERIOD=(SELECT MIN(Y.FINANCIALPERIOD) 
FROM FINANCIALPERIODS Y
WHERE  Y.ORGID='&1' AND NVL(Y.CLOSEDBY,' ') NOT LIKE '%MOT%'));

SPOOL OFF;

/
