REM **************************************************************************
REM
REM PROGRAM NAME : WAREHOUSE_FEEDER_MTH04.SQL
REM
REM PURPOSE      : TO OBTAIN NUMBER OF RECORDS WRITTEN TO
REM                INVOICE  TABLE FOR THE GIVEN MONTH
REM
REM DATE         : 05/09/12 
REM
REM AUTHOR       : PANKAJ BHIDE
REM
REM MODIFICIATION
REM     HISTORY  : 
REM **************************************************************************
SET HEADING OFF
SET FEEDBACK OFF
SET TERMOUT OFF
SET ECHO OFF
SET PAGESIZE 0
SET SPACES 0
SET NEWPAGE 0
SET LINESIZE 6
SET VERIFY OFF

SPOOL warehouse_cnt

SELECT RTRIM(LTRIM(TO_CHAR(COUNT(*),'999999')))
FROM MAXIMO.INVOICE
WHERE  ORGID='&1'
AND    SITEID='&2'
AND    INVOICENUM LIKE 'WAREHOUSE%'
AND TRUNC(INVOICEDATE) =(SELECT TRUNC(X.PERIODEND-1)
FROM   FINANCIALPERIODS X
WHERE  X.ORGID='&1' AND X.FINANCIALPERIOD=(SELECT MIN(Y.FINANCIALPERIOD) 
FROM FINANCIALPERIODS Y
WHERE  Y.ORGID='&1' AND NVL(Y.CLOSEDBY,' ') NOT LIKE '%STR%'));

SPOOL OFF;

/
