/*****************************************************************
  UPDATE USERIDS FOR LDAP INTEGRATION   
  NOTE: TAKE BACKUP OF MAXUSER TABLE BEFORE RUNNING THIS PROGRAM 
  CREATE TABLE LBL_MAXUSER AS SELECT * FROM MAXUSER;
  
  AUTHOR: PANKAJ BHIDE
  
  DATE:  JUL 2, 2015
  
 ***************************************************************/
DECLARE CURSOR MAXUSER_CUR IS
  SELECT LOGINID, PERSONID 
  FROM MAXUSER
  WHERE STATUS='ACTIVE' AND LOGINID NOT IN ('IT-BS-MXINTADM') FOR UPDATE;
  
  T_NEWUSERID VARCHAR2(100);
BEGIN

  FOR MAXUSER_REC IN MAXUSER_CUR
    LOOP
      T_NEWUSERID :=NULL;
      
      BEGIN
        SELECT TRIM(SUBSTR(EMAILADDRESS,1,INSTR(EMAILADDRESS,'@')-1)) 
        INTO T_NEWUSERID
        FROM EMAIL 
        WHERE PERSONID=MAXUSER_REC.PERSONID;
        
        IF (T_NEWUSERID IS NOT NULL) THEN 
          UPDATE MAXUSER
          SET LOGINID=T_NEWUSERID
          WHERE PERSONID=MAXUSER_REC.PERSONID;
        END IF;
        
      EXCEPTION WHEN OTHERS THEN  
        NULL;
      END;
      
   END LOOP;
   
END;

COMMIT;
/
      
      
        
