


delete from lbl_maxvars;
 
Insert into MAXIMO.LBL_MAXVARS (LBL_MAXVARSID,DESCRIPTION,ORGID,SITEID,VARNAME,VARVALUE,HASLD,ROWSTAMP) values (LBL_MAXVARSIDSEQ1.nextval,'Length of work order number','LBNL','FAC','LBL_WOLENGTH','8',0,'409269694');
Insert into MAXIMO.LBL_MAXVARS (LBL_MAXVARSID,DESCRIPTION,ORGID,SITEID,VARNAME,VARVALUE,HASLD,ROWSTAMP) values (LBL_MAXVARSIDSEQ1.nextval,null,'LBNL','FAC','LAST_WOREQ_NUM','17',0,'409269695');
Insert into MAXIMO.LBL_MAXVARS (LBL_MAXVARSID,DESCRIPTION,ORGID,SITEID,VARNAME,VARVALUE,HASLD,ROWSTAMP) values (LBL_MAXVARSIDSEQ1.nextval,null,'LBNL','FAC','LOCKSHOP_SUPERVISOR','175351',0,'409269696');
Insert into MAXIMO.LBL_MAXVARS (LBL_MAXVARSID,DESCRIPTION,ORGID,SITEID,VARNAME,VARVALUE,HASLD,ROWSTAMP) values (LBL_MAXVARSIDSEQ1.nextval,null,'LBNL','FAC','RADIOSHOP_SUPERVISOR','651432',0,'409269697');
Insert into MAXIMO.LBL_MAXVARS (LBL_MAXVARSID,DESCRIPTION,ORGID,SITEID,VARNAME,VARVALUE,HASLD,ROWSTAMP) values (LBL_MAXVARSIDSEQ1.nextval,null,'LBNL','FAC','WOREQ_TRANSP_<250_LEADCRAFT','FASST',0,'409269698');
Insert into MAXIMO.LBL_MAXVARS (LBL_MAXVARSID,DESCRIPTION,ORGID,SITEID,VARNAME,VARVALUE,HASLD,ROWSTAMP) values (LBL_MAXVARSIDSEQ1.nextval,null,'LBNL','FAC','WOREQ_TRANSP_<250_SUPERVISOR','010971',0,'409269699');
Insert into MAXIMO.LBL_MAXVARS (LBL_MAXVARSID,DESCRIPTION,ORGID,SITEID,VARNAME,VARVALUE,HASLD,ROWSTAMP) values (LBL_MAXVARSIDSEQ1.nextval,null,'LBNL','FAC','WOREQ_TRANSP_>250_LEADCRAFT','FASST',0,'409269700');
Insert into MAXIMO.LBL_MAXVARS (LBL_MAXVARSID,DESCRIPTION,ORGID,SITEID,VARNAME,VARVALUE,HASLD,ROWSTAMP) values (LBL_MAXVARSIDSEQ1.nextval,null,'LBNL','FAC','STR03_FEEDER_NAME','SIS',0,'409269701');
Insert into MAXIMO.LBL_MAXVARS (LBL_MAXVARSID,DESCRIPTION,ORGID,SITEID,VARNAME,VARVALUE,HASLD,ROWSTAMP) values (LBL_MAXVARSIDSEQ1.nextval,null,'LBNL','FAC','FRST_WO_APPR_DT','10/01/2010',0,'409269702');
Insert into MAXIMO.LBL_MAXVARS (LBL_MAXVARSID,DESCRIPTION,ORGID,SITEID,VARNAME,VARVALUE,HASLD,ROWSTAMP) values (LBL_MAXVARSIDSEQ1.nextval,null,'LBNL','FAC','WOREQ_TRANSP_>250_SUPERVISOR','010971',0,'409269703');
Insert into MAXIMO.LBL_MAXVARS (LBL_MAXVARSID,DESCRIPTION,ORGID,SITEID,VARNAME,VARVALUE,HASLD,ROWSTAMP) values (LBL_MAXVARSIDSEQ1.nextval,null,'LBNL','FAC','HAZARDID','3175',0,'409269704');
Insert into MAXIMO.LBL_MAXVARS (LBL_MAXVARSID,DESCRIPTION,ORGID,SITEID,VARNAME,VARVALUE,HASLD,ROWSTAMP) values (LBL_MAXVARSIDSEQ1.nextval,null,'LBNL','FAC','PRECAUTIONID','2844',0,'409269705');
Insert into MAXIMO.LBL_MAXVARS (LBL_MAXVARSID,DESCRIPTION,ORGID,SITEID,VARNAME,VARVALUE,HASLD,ROWSTAMP) values (LBL_MAXVARSIDSEQ1.nextval,'Application environment','LBNL','FAC','APP_ENVIRONMENT','DEVELOPMENT',0,'409269706');
Insert into MAXIMO.LBL_MAXVARS (LBL_MAXVARSID,DESCRIPTION,ORGID,SITEID,VARNAME,VARVALUE,HASLD,ROWSTAMP) values (LBL_MAXVARSIDSEQ1.nextval,'Length of walk through number','LBNL','FAC','LBL_WKTRHULENGTH','9',0,'409269707');
Insert into MAXIMO.LBL_MAXVARS (LBL_MAXVARSID,DESCRIPTION,ORGID,SITEID,VARNAME,VARVALUE,HASLD,ROWSTAMP) values (LBL_MAXVARSIDSEQ1.nextval,null,'LBNL','FAC','LAST_MONTHLY_ACTUALS_TO_MAXIMO','201505',0,'409269708');
Insert into MAXIMO.LBL_MAXVARS (LBL_MAXVARSID,DESCRIPTION,ORGID,SITEID,VARNAME,VARVALUE,HASLD,ROWSTAMP) values (LBL_MAXVARSIDSEQ1.nextval,null,'LBNL','FAC','WOREQ_PEOPLE_LEADCRAFT','FAPLG',0,'409269709');
Insert into MAXIMO.LBL_MAXVARS (LBL_MAXVARSID,DESCRIPTION,ORGID,SITEID,VARNAME,VARVALUE,HASLD,ROWSTAMP) values (LBL_MAXVARSIDSEQ1.nextval,null,'LBNL','FAC','WOREQ_PEOPLE_SUPERVISOR','040029',0,'409269710');
Insert into MAXIMO.LBL_MAXVARS (LBL_MAXVARSID,DESCRIPTION,ORGID,SITEID,VARNAME,VARVALUE,HASLD,ROWSTAMP) values (LBL_MAXVARSIDSEQ1.nextval,null,'LBNL','FAC','WOREQ_CONF_TABLES_SUPERVISOR','010971',0,'409269711');
Insert into MAXIMO.LBL_MAXVARS (LBL_MAXVARSID,DESCRIPTION,ORGID,SITEID,VARNAME,VARVALUE,HASLD,ROWSTAMP) values (LBL_MAXVARSIDSEQ1.nextval,null,'LBNL','FAC','WOREQ_CONF_TABLES_LEADCRAFT','FAOMC',0,'409269712');
Insert into MAXIMO.LBL_MAXVARS (LBL_MAXVARSID,DESCRIPTION,ORGID,SITEID,VARNAME,VARVALUE,HASLD,ROWSTAMP) values (LBL_MAXVARSIDSEQ1.nextval,null,'LBNL','FAC','WOREQ_CONF_NON_TABLES_SUPERVISOR','558003',0,'409269713');
Insert into MAXIMO.LBL_MAXVARS (LBL_MAXVARSID,DESCRIPTION,ORGID,SITEID,VARNAME,VARVALUE,HASLD,ROWSTAMP) values (LBL_MAXVARSIDSEQ1.nextval,'Work order release app URL','LBNL','FAC','WOREL_URL','https://worelease.dev.lbl.gov',0,'409269714');
Insert into MAXIMO.LBL_MAXVARS (LBL_MAXVARSID,DESCRIPTION,ORGID,SITEID,VARNAME,VARVALUE,HASLD,ROWSTAMP) values (LBL_MAXVARSIDSEQ1.nextval,null,'LBNL','FAC','WOREQ_CONF_NON_TABLES_LEADCRAFT','FASSJ',0,'409269715');
Insert into MAXIMO.LBL_MAXVARS (LBL_MAXVARSID,DESCRIPTION,ORGID,SITEID,VARNAME,VARVALUE,HASLD,ROWSTAMP) values (LBL_MAXVARSIDSEQ1.nextval,null,'LBNL','FAC','WOREQ_CUSTODIAL_LEADCRAFT','FAOMC',0,'409269716');
Insert into MAXIMO.LBL_MAXVARS (LBL_MAXVARSID,DESCRIPTION,ORGID,SITEID,VARNAME,VARVALUE,HASLD,ROWSTAMP) values (LBL_MAXVARSIDSEQ1.nextval,null,'LBNL','FAC','WOREQ_CUSTODIAL_SUPERVISOR','558003',0,'409269717');
Insert into MAXIMO.LBL_MAXVARS (LBL_MAXVARSID,DESCRIPTION,ORGID,SITEID,VARNAME,VARVALUE,HASLD,ROWSTAMP) values (LBL_MAXVARSIDSEQ1.nextval,'Facilities WPC Email','LBNL','FAC','FACWPC_EMAIL','pbhide@lbl.gov',0,'409269718');
Insert into MAXIMO.LBL_MAXVARS (LBL_MAXVARSID,DESCRIPTION,ORGID,SITEID,VARNAME,VARVALUE,HASLD,ROWSTAMP) values (LBL_MAXVARSIDSEQ1.nextval,'Help URL for TAWD application','LBNL','FAC','TAWDHELP_URL','https://tad.dev.lbl.gov/general/tawd_help.aspx',0,'409269719');

commit;
