


create table lbl_ApplicationAuth as select * from ApplicationAuth;

--insert into ApplicationAuth select * from lbl_ApplicationAuth;

--commit;




delete from applicationauth
 where optionname in ('DELETE','INSERT','SAVE','DUPLICATE','PASSWORD',
'STATUS','ASSIGNWF','WMATL','INIT','ROUTEWF','MANAGEFOLD','MANAGELIB','METHISTUPD',
'METHIST','METHISTUPD','COMP','INPRG','APPR','UNDOAPPR','WMATL','ASGNEWPRNT',
'CANCEL','STATUS;','CREATECOMM','CREATEWO','MASSMOVE','UNDOAPPR',
'APPLYSLA','CONFIGURE','CLOSED','CREATECOMM','STOPWF','CREATESR',
'CREATEWO','METRESET','LOCSTATUS','USERCUST','UPDATETEMP','INVLINES',
'STOPWF','FNSHASSN','INTRPTASSN','MODIFYWO','REVISE','COPYLNK2WO','WSCH',
'ASSIGNWF','ROUTEWF','REMOVEWP','PMCOM_LAUNCH','EDITREPT',
'REPDOWN','SAVE','UNDOAPPR','CHGHIST','CREATEREPT','EDITREPT',
'CREATECIS','INPROG','MODDELWL','MODIFYSLAS','CLOSE','WO_SLAS',
'OWNERSHIP','PENDING','QUEUED','RESOLVED','OWNER','LBLWO2WKTH','NEWWRKPKG',
'SIMILARTKT','STARTTIMER','STOPTIMER','TEMPLATE','RELATERECORD',
'TKCOMMLOG','TKWORKLOG','EDITHIST','DELETEREPT','HISTORYWF','METERREAD',
'CREATECHNG','MEMOABOVESTATUS','MEMOBELOWSTATUS',
'CREATEINC','APPLYRTE','ASSIGN','PUBLICREPT', 'CREATEJP','ASTDETAILS',
'CREATEKPI', 'CREATECHG','NEWWRKPKG',
'CREATEPROB','MOVEASSET','SWAPASSET','ASTLOCCOMM','ALTERITEM','APPLYIAS',
'CREATEREL','ASMOVEHIST','ASMOVEHIST','ZEROYTD','SWAPASSET',
'REMOVESP','UPDAVUNITS','INVTRANS','ISSUE','ITEMAVAIL','KITMAKE',
'APPLYRTE','APPROVE','ALLOCSEV','AVGCOSTADJ','CHANGEVEND','CURBALADJ',
'METREADNEW','CAPCSTADG','DEFSELCRIT','EDITRESV','HOLD','KITBREAK',
'METREADOLD','PHYSCNTADJ','POORD','PAID','RECONCILE','REORDER',
'METREADNEW','REORISS','RELLOCKS','RESITEMS','RETURNS','STATHIST',
'METREADOLD','STDCOSTADJ','TRANSFER','WAITAPPR','TRANSFERS',
'CREATEINCT','GENERATEWO','WOTRACK','MNGPPCODE',
'CREATEJP','WKTHRUDUP','MNGPPCODE',
'CREATESREQ',
'ADDITEMS',
'COMMCODE','CONVERSION','MEASUNIT','CAPCSTADG','COPYIAS','ITEMORG');

commit;
