---------------------------------
-- PLEASE MAKE LBL_MAXUSERS EXIST
-----------------------------------

DELETE FROM MAXUSERS WHERE EXISTS (SELECT 1 FROM LBL_MAXUSERS); 

INSERT INTO MAXUSERS SELECT * FROM lbl_maxuser;

COMMIT;

CREATE TABLE LBL_MAXSESSION6 AS SELECT * FROM MAXSESSION;

CREATE TABLE LBL_LOGINTRACKING6 AS SELECT * FROM logintracking;

DELETE FROM MAXSESSION;

DELETE FROM logintracking;

COMMIT;
