-- Start of DDL Script for View MAXIMO.LBL_V_WOWREL
-- Generated 14-Oct-2015 11:12:00 from MAXIMO@mmoprd

CREATE OR REPLACE VIEW lbl_v_wowrel (
   wonum,
   description,
   long_description,
   reportedby,
   reportedby_name,
   reportedby_division,
   reportedby_phone,
   reportdate,
   supervisor,
   supervisor_details,
   location,
   building,
   room,
   glaccount,
   glaccount_description,
   status_description,
   worktype,
   worktype_description,
   status,
   status_date,
   schedstartdate,
   schedenddate,
   targstartdate,
   targenddate,
   escort_reqd,
   cond_release,
   comments_cond_release,
   personid,
   workorderid )
AS
SELECT A.WONUM, LBL_MAXIMO_PKG.REPLACE_NON_ASCII(NVL(A.DESCRIPTION,'BLANK'),' ') DESCRIPTION,  
NVL(LBL_MAXIMO_PKG.GET_LONGDESCRIPTION(A.WORKORDERID,'WORKORDER','DESCRIPTION'),' ') LONG_DESCRIPTION, 
NVL(A.REPORTEDBY,' ') REPORTEDBY, NVL(P2.DISPLAYNAME,' ') REPORTEDBY_NAME, NVL(P2.LBL_ORG_LEVEL_1,' ') REPORTEDBY_DIVISION, 
NVL(PH.PHONENUM, ' ') REPORTEDBY_PHONE, 
TO_CHAR(A.REPORTDATE,'MM/DD/YYYY') REPORTDATE, 
NVL(A.SUPERVISOR,' ') SUPERVISOR, NVL(P1.DISPLAYNAME,' ') SUPERVISOR_DETAILS,
NVL(A.LOCATION, ' ') LOCATION,  
NVL(LOC.LO1,' ') BUILDING,  NVL(LOC.LO3,' ')  ROOM, 
NVL(A.GLACCOUNT,' ') GLACCOUNT, NVL(COA.ACCOUNTNAME,' ') GLACCOUNT_DESCRIPTION,  
SYN.DESCRIPTION  STATUS_DESCRIPTION,  
NVL(A.WORKTYPE,' ') WORKTYPE, NVL(WTP.WTYPEDESC,' ') WORKTYPE_DESCRIPTION,  
A.STATUS, TO_CHAR(A.STATUSDATE,'MM/DD/YYYY') STATUS_DATE,   
NVL(TO_CHAR(A.SCHEDSTART,'MM/DD/YYYY'),' ') SCHEDSTARTDATE,  
NVL(TO_CHAR(A.SCHEDFINISH,'MM/DD/YYYY'),' ') SCHEDENDDATE,  
NVL(TO_CHAR(A.TARGSTARTDATE,'MM/DD/YYYY'),' ') TARGSTARTDATE,  
NVL(TO_CHAR(A.TARGCOMPDATE,'MM/DD/YYYY'), ' ') TARGENDDATE,  
( 
  CASE WHEN (LOC.LBL_ESCORT_REQD != A.LBL_ESCORT_REQD)  THEN A.lbl_escort_reqd
  ELSE NVL(LOC.lbl_escort_reqd,'N')
  END
 ) ESCORT_REQD,
(
  CASE WHEN (LOC.LBL_COND_RELEASE != A.lbl_condition_rel)  THEN A.lbl_condition_rel
  ELSE NVL(LOC.LBL_COND_RELEASE,'N')
  END
 ) COND_RELEASE,
  
(
 CASE WHEN LBL_MAXIMO_PKG.GET_LONGDESCRIPTION(A.WORKORDERID,'WORKORDER','LBL_CONDITION_REL') IS NULL THEN NVL(LOC.LBL_COMMENTS_CONDR,' ') 
 ELSE LBL_MAXIMO_PKG.GET_LONGDESCRIPTION(A.WORKORDERID,'WORKORDER','LBL_CONDITION_REL') 
 END
) COMMENTS_COND_RELEASE ,

C.PERSONID,
A.WORKORDERID 
FROM MAXIMO.WORKORDER A   
LEFT OUTER JOIN MAXIMO.PERSON P1 ON  
A.SUPERVISOR=P1.PERSONID LEFT OUTER JOIN MAXIMO.PERSON P2 ON  
A.REPORTEDBY=P2.PERSONID LEFT OUTER JOIN MAXIMO.PHONE PH ON   
A.REPORTEDBY=PH.PERSONID AND PH.ISPRIMARY=1   
LEFT OUTER JOIN   MAXIMO.CHARTOFACCOUNTS COA ON 
A.GLACCOUNT=COA.GLACCOUNT, 
MAXIMO.WORKTYPE WTP,  
MAXIMO.LOCATIONS LOC, MAXIMO.SYNONYMDOMAIN SYN,
MAXIMO.LBL_AUTH_RELEASE C,
MAXIMO.PERSON  B 
WHERE WTP.ORGID='LBNL'  AND A.WORKTYPE=WTP.WORKTYPE   
AND   A.ORGID='LBNL' AND A.SITEID='FAC'
AND   A.LOCATION=LOC.LOCATION 
AND   SYN.DOMAINID='WOSTATUS' AND SYN.VALUE=A.STATUS 
AND   A.STATUS='WREL'  
AND   A.ISTASK=0   
AND   A.LOCATION=C.LOCATION
AND   C.PERSONID=B.PERSONID 
AND   B.LBL_STATUS='A'  
ORDER BY A.WONUM
/

-- Grants for View
GRANT DELETE ON lbl_v_wowrel TO public
/
GRANT INSERT ON lbl_v_wowrel TO public
/
GRANT SELECT ON lbl_v_wowrel TO public
/
GRANT UPDATE ON lbl_v_wowrel TO public
/
GRANT REFERENCES ON lbl_v_wowrel TO public
/
GRANT ON COMMIT REFRESH ON lbl_v_wowrel TO public
/
GRANT QUERY REWRITE ON lbl_v_wowrel TO public
/
GRANT DEBUG ON lbl_v_wowrel TO public
/
GRANT FLASHBACK ON lbl_v_wowrel TO public
/
GRANT MERGE VIEW ON lbl_v_wowrel TO public
/

-- End of DDL Script for View MAXIMO.LBL_V_WOWREL

