CREATE OR REPLACE PACKAGE lbl_maximo_query AS

FUNCTION NUM_CHILD_WITH_MATERIALS(V_WONUM IN MAXIMO.WORKORDER.WONUM%TYPE)
                RETURN NUMBER;

FUNCTION GET_MONTHLY_VEHICLE_DETAILS(ASSETNUM_I IN MAXIMO.ASSET.ASSETNUM%TYPE,
FINANCIALPERIOD_I IN MAXIMO.FINANCIALPERIODS.financialperiod%TYPE,
TYPE_I  VARCHAR2)
        RETURN NUMBER;

FUNCTION IS_VEHICLE_USEABLE(ASSETNUM_I IN MAXIMO.ASSET.ASSETNUM%TYPE,
FINANCIALPERIOD_I IN MAXIMO.FINANCIALPERIODS.financialperiod%TYPE)
        RETURN VARCHAR2;


FUNCTION GET_WORKORDER_DATE(ORGID_I  IN WORKORDER.ORGID%TYPE,
                            SITEID_I IN WORKORDER.ORGID%TYPE,
                            WONUM_I  IN WORKORDER.WONUM%TYPE,
                            TYPE_I   IN WORKORDER.DESCRIPTION%TYPE)
RETURN DATE;


END LBL_MAXIMO_QUERY;
