CREATE OR REPLACE PACKAGE LBNL_UPDT_PACKAGE
AUTHID DEFINER IS


FUNCTION INSERT_LOCATION_TABLES(LOCATION_I IN LOCATIONS.LOCATION%TYPE,
                                PARENT_I		IN LOCHIERARCHY.PARENT%TYPE,
                                DESCRIPTION_I           IN LOCATIONS.DESCRIPTION%TYPE,
                                CHANGEBY_I IN LOCATIONS.CHANGEBY%TYPE)
          RETURN VARCHAR2;

FUNCTION UPDATE_FEEDER_CLOSE(FINANCIALPERIOD_I IN FINANCIALPERIODS.FINANCIALPERIOD%TYPE,
                            FEEDER_NAME_I      IN FINANCIALPERIODS.CLOSEDBY%TYPE,
                            ORGID_I            IN FINANCIALPERIODS.ORGID%TYPE)

          RETURN VARCHAR2;

FUNCTION INSERT_LBL_VEHMILEHISTORY(ASSETNUM_I         IN ASSET.ASSETNUM%TYPE,
                                   METERREADING_I  IN ASSETMETER.LASTREADING%TYPE,
                                   READINGDATE_I   IN ASSETMETER.LASTREADINGDATE%TYPE,
				                   ORGID_I         IN ASSET.ORGID%TYPE,
				                    SITEID_I       IN ASSET.SITEID%TYPE)
                                   RETURN VARCHAR2;


PRAGMA RESTRICT_REFERENCES (INSERT_LOCATION_TABLES,RNPS,WNPS);
PRAGMA RESTRICT_REFERENCES (UPDATE_FEEDER_CLOSE,RNPS,WNPS);
PRAGMA RESTRICT_REFERENCES (INSERT_LBL_VEHMILEHISTORY,RNPS,WNPS);

END;
