CREATE OR REPLACE PACKAGE LBL_MAXIMO_FEEDBACK
IS
 FUNCTION GET_LAST_STATUS(
          ORGID_I   IN MAXIMO.WORKORDER.ORGID%TYPE,
          SITEID_I  IN MAXIMO.WORKORDER.SITEID%TYPE,
          WONUM_I   IN MAXIMO.WORKORDER.WONUM%TYPE,
          STATUS_I  IN MAXIMO.WOSTATUS.STATUS%TYPE)
          RETURN MAXIMO.WORKORDER.STATUS%TYPE;


 PROCEDURE INSERT_UPD_LBL_WOFEEDBACK(
 ORGID_I    IN MAXIMO.WORKORDER.ORGID%TYPE,
 SITEID_I   IN MAXIMO.WORKORDER.SITEID%TYPE,
 WONUM_I    IN MAXIMO.WORKORDER.WONUM%TYPE,
 ID_I       IN BATCH_MAXIMO.LBL_WOFEEDBACK.ID%TYPE,
 CUSTOMERID_I IN BATCH_MAXIMO.LBL_WOFEEDBACK.CUSTOMERID%TYPE,
 VALUE_I    IN BATCH_MAXIMO.LBL_WOFEEDBACK.VALUE%TYPE,
 CHANGEBY_I IN BATCH_MAXIMO.LBL_WOFEEDBACK.CHANGEBY%TYPE,
 WOFEEDBACKID_I IN BATCH_MAXIMO.LBL_WOFEEDBACK.WOFEEDBACKID%TYPE );


 PROCEDURE INSERT_UPD_WOFEEDBACKCOMMENTS(
 ORGID_I    IN MAXIMO.WORKORDER.ORGID%TYPE,
 SITEID_I   IN MAXIMO.WORKORDER.SITEID%TYPE,
 WONUM_I IN MAXIMO.WORKORDER.WONUM%TYPE,
 CUSTOMERID_I IN BATCH_MAXIMO.LBL_WOFEEDBACKCOMMENTS.CUSTOMERID%TYPE,
 RESPTOCOMMENTS_I    IN BATCH_MAXIMO.LBL_WOFEEDBACKCOMMENTS.RESPTOCOMMENTS%TYPE,
 COMMENTS_I IN BATCH_MAXIMO.LBL_WOFEEDBACKCOMMENTS.COMMENTS%TYPE,
 CHANGEBY_I IN BATCH_MAXIMO.LBL_WOFEEDBACKCOMMENTS.CHANGEBY%TYPE,
 CONTACT_NAME_I      IN BATCH_MAXIMO.LBL_WOFEEDBACKCOMMENTS.CONTACT_NAME%TYPE,
 CONTACT_DETAILS_I   IN BATCH_MAXIMO.LBL_WOFEEDBACKCOMMENTS.CONTACT_DETAILS%TYPE,
 WOFEEDBACKID_I      IN BATCH_MAXIMO.LBL_WOFEEDBACKCOMMENTS.WOFEEDBACKID%TYPE );


END;
