CREATE OR REPLACE PACKAGE BODY LBL_MERIDIAN_IFACE
IS


PROCEDURE INS_LBL_MERIDIAN_ARCHIVE(
     P_ID IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.ID%TYPE,
     P_CYCOSTATUS IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.CYCOSTATUS%TYPE,
     P_PROJECT_NM IN BATCH_MAXIMO. LBL_MERIDIAN_ARCHIVE.PROJECT_NM%TYPE,
     P_DRAWING_NM IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.DRAWING_NM%TYPE,
     P_FILENAME IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.FILENAME%TYPE ,
     P_DRAWN_BY IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.DRAWN_BY%TYPE,
     P_DATEISSUED IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.DATEISSUED%TYPE,
     P_DATE_REV_1 IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.DATE_REV_1%TYPE,
     P_ISSUEAPPBY IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.ISSUEAPPBY%TYPE,
     P_REV1APPRBY IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.REV1APPRBY%TYPE,
     P_PART_OFSET IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.PART_OFSET%TYPE,
     P_PHASE IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.PHASE%TYPE,
     P_VERSION IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.VERSION%TYPE,
     P_DWG_STATUS IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.DWG_STATUS%TYPE,
     P_DATEDWGSTA IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.DATEDWGSTA%TYPE,
     P_TODO IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.TODO%TYPE,
     P_TOBEDONEBY IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.TOBEDONEBY%TYPE,
     P_DATETOBEDN IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.DATETOBEDN%TYPE,
     P_NOTES1 IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.NOTES1%TYPE,
     P_NOTES2 IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.NOTES2%TYPE,
     P_DRAWING_FN IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.DRAWING_FN%TYPE,
     P_DRAWING_NR IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.DRAWING_NR%TYPE,
     P_TITLESHEET IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.TITLESHEET%TYPE,
     P_SCALE IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.SCALE%TYPE,
     P_EXTENSION IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.EXTENSION%TYPE,
     P_BLDG_NAME IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.BLDG_NAME%TYPE,
     P_DISCIPLINE IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.DISCIPLINE%TYPE,
     P_F_NAME IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.F_NAME%TYPE,
     P_SHEET_NO IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.SHEET_NO%TYPE,
     P_CHK_BY IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.CHK_BY%TYPE,
     P_CHK_DATE IN BATCH_MAXIMO. LBL_MERIDIAN_ARCHIVE.CHK_DATE%TYPE,
     P_CON_DOC IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.CON_DOC%TYPE,
     P_CON_DATE IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.CON_DATE%TYPE,
     P_APPROVED IN BATCH_MAXIMO. LBL_MERIDIAN_ARCHIVE.APPROVED%TYPE,
     P_APP_DATE IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.APP_DATE%TYPE,
     P_REVISION IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.REVISION%TYPE,
     P_DRWN_DATE IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.DRWN_DATE%TYPE,
     P_SHEET_SIZE IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.SHEET_SIZE%TYPE,
     P_FIRE_APP IN BATCH_MAXIMO. LBL_MERIDIAN_ARCHIVE.FIRE_APP%TYPE,
     P_FIRE_DATE IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.FIRE_DATE%TYPE,
     P_AE_NAME IN BATCH_MAXIMO. LBL_MERIDIAN_ARCHIVE.AE_NAME%TYPE,
     P_PROJ_TITLE IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.PROJ_TITLE%TYPE,
     P_BLDG_LOC IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.BLDG_LOC%TYPE,
     P_BLDG_DESCP IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.BLDG_DESCP%TYPE,
     P_FILE_NM IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.FILE_NM%TYPE,
     P_GLOBALID IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.GLOBALID%TYPE,
     P_LOCKFLAG IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.LOCKFLAG%TYPE,
     P_REVFLAG IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.REVFLAG%TYPE,
     P_TEMP IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.TEMP%TYPE,
     P_ISSUESTAT IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.ISSUESTAT%TYPE,
     P_SHEETTOTL IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.SHEETTOTL%TYPE,
     P_PROJECT_NR IN BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.PROJECT_NR%TYPE,
     O_OUTPUT OUT BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE.SHEETTOTL%TYPE
     )


     IS

     BEGIN


     INSERT INTO BATCH_MAXIMO.LBL_MERIDIAN_ARCHIVE
     (ID,
      CYCOSTATUS, PROJECT_NM,  DRAWING_NM, FILENAME,
      DRAWN_BY, DATEISSUED, DATE_REV_1, ISSUEAPPBY, REV1APPRBY,
      PART_OFSET, PHASE,
      VERSION, DWG_STATUS, DATEDWGSTA, TODO, TOBEDONEBY, DATETOBEDN,
      NOTES1, NOTES2,
      DRAWING_FN, DRAWING_NR, TITLESHEET, SCALE, EXTENSION, BLDG_NAME,
      DISCIPLINE, F_NAME,
      SHEET_NO, CHK_BY, CHK_DATE, CON_DOC, CON_DATE, APPROVED, APP_DATE,
      REVISION,   DRWN_DATE, SHEET_SIZE, FIRE_APP, FIRE_DATE,AE_NAME,
      PROJ_TITLE, BLDG_LOC, BLDG_DESCP,
      FILE_NM, GLOBALID, LOCKFLAG, REVFLAG, TEMP, ISSUESTAT, SHEETTOTL, PROJECT_NR)
     VALUES
     (P_ID,
       P_CYCOSTATUS, P_PROJECT_NM,  P_DRAWING_NM, P_FILENAME,
       P_DRAWN_BY, NVL(P_DATEISSUED,NULL), P_DATE_REV_1, P_ISSUEAPPBY, P_REV1APPRBY ,
       P_PART_OFSET, P_PHASE,
       P_VERSION, P_DWG_STATUS, P_DATEDWGSTA, P_TODO, P_TOBEDONEBY, NVL(P_DATETOBEDN,NULL),
       P_NOTES1, P_NOTES2,
       P_DRAWING_FN, P_DRAWING_NR, P_TITLESHEET, P_SCALE, P_EXTENSION, P_BLDG_NAME,
       P_DISCIPLINE, P_F_NAME,
       P_SHEET_NO, P_CHK_BY, NVL(P_CHK_DATE,NULL), P_CON_DOC, NVL(P_CON_DATE,NULL), P_APPROVED, NVL(P_APP_DATE,NULL),
       P_REVISION, NVL(P_DRWN_DATE,NULL), P_SHEET_SIZE, P_FIRE_APP, NVL(P_FIRE_DATE,NULL),P_AE_NAME,
       P_PROJ_TITLE, P_BLDG_LOC, P_BLDG_DESCP,
       P_FILE_NM, P_GLOBALID, P_LOCKFLAG, P_REVFLAG, P_TEMP, P_ISSUESTAT, P_SHEETTOTL, P_PROJECT_NR);


      O_OUTPUT :='1';

END;





END;
