CREATE OR REPLACE PACKAGE lbl_workreq_pkg
IS
/*****************************************************************************
 PROGRAM NAME           : LBL_WOREQ_PKG

 DATE WRITTEN           : 01-JUL-2008

 AUTHOR                 : PANKAJ BHIDE

 PURPOSE                : PACKAGE SPECS FOR DATABASE INSERT/UPDATE REQUIRED
                          FOR WORK REQUEST APPLICATION

                         APR 21, 2010 - ADDED SERVICE TYPE

                         MAY 12, 2010 - ADDED COMMODITY GROUP FOR MODS

                         AUGUST 12, 2010 - GET EMPLOYEE DETAILS

                         FEB 28, 2011 - GET RELEASE STATUS FOR LOCATION

                         JAN 15, 2013 - SET CALCPRIORITY AND ASSETLOCPRIORITY

                         JUN 26, 2013 - CHANGES FOR WPC PHASE-2 PROJECT

                         FEB 04, 2015 - CHANGES FOR MAXIMO 7.5 UPGRADE

                         MAR 14  2016 - ESTIMATE WORK REQUEST
*****************************************************************************/


FUNCTION GET_NEXT_NUMBER(TYPE_I IN MAXIMO.WORKORDER.DESCRIPTION%TYPE)
RETURN MAXIMO.WORKORDER.WONUM%TYPE;

/**********************************************
* FUNCTION TO GET RELEASE STATUS FOR A LOCATION
***********************************************/
FUNCTION GET_RELEASE_LOCATION(
  LOCATION_I             IN LOCATIONS.LOCATION%TYPE)
  RETURN MAXIMO.WORKORDER.DESCRIPTION%TYPE;



/**********************************************
* FUNCTION TO PRIORITY FOR THE LOCATION
***********************************************/
FUNCTION GET_LOC_PRIORITY(
  LOCATION_I             IN LOCATIONS.LOCATION%TYPE)
  RETURN MAXIMO.WORKORDER.ASSETLOCPRIORITY%TYPE;



FUNCTION INSERT_GEN_WORKREQ(
    I_REPORTEDBY                IN    WORKORDER.REPORTEDBY%TYPE,
    I_PHONE                     IN    WORKORDER.PHONE%TYPE,
    I_WO1                       IN    WORKORDER.WO1%TYPE,
    I_WO1_PHONE                 IN    LBL_WORKORDEREXT.WO1_PHONE%TYPE,
    I_BUILDING                  IN    LBL_WORKORDEREXT.BUILDING%TYPE,
    I_ROOM                      IN    LBL_WORKORDEREXT.ROOM%TYPE,
    I_LOCATION_NOTES            IN    LBL_WORKORDEREXT.LOCATION_NOTES%TYPE,
    I_FIRST_AVL_DATETIME        IN    LBL_WORKORDEREXT.FIRST_AVL_DATETIME%TYPE,
    I_TARGSTARTDATE             IN    VARCHAR2, --LBL_WORKORDEREXT.TARGSTARTDATE%TYPE, MM/DD/YYYY
    I_TARGCOMPDATE              IN    VARCHAR2, --LBL_WORKORDEREXT.TARGCOMPDATE%TYPE, MM/DD/YYYY
    I_SCHED_ISSUES              IN    LBL_WORKORDEREXT.SCHED_ISSUES%TYPE,
    I_SCHED_ISSUES_DTL          IN    LBL_WORKORDEREXT.SCHED_ISSUES_DTL%TYPE,
    I_BUILDING_MAINT            IN    LBL_WORKORDEREXT.BUILDING_MAINT%TYPE,
    I_GLACCOUNT                 IN    WORKORDER.GLACCOUNT%TYPE,
    I_DESCRIPTION               IN    WORKORDER.DESCRIPTION%TYPE,
    I_ACCOMP_COND_PROB          IN    LBL_WORKORDEREXT.ACCOMP_COND_PROB%TYPE,
    I_COMMODITYGROUP            IN    WORKORDER.COMMODITYGROUP%TYPE,
    I_COMMODITY                 IN    WORKORDER.COMMODITY%TYPE,
    I_PRIOR_WO                  IN    LBL_WORKORDEREXT.PRIOR_WO%TYPE,
    I_PRIOR_WONUM               IN    LBL_WORKORDEREXT.PRIOR_WONUM%TYPE,
    I_ASSET_DESC                IN    LBL_WORKORDEREXT.ASSET_DESC%TYPE,
    I_WARRANTY_ISSUE            IN    LBL_WORKORDEREXT.WARRANTY_ISSUE%TYPE,
    I_WARRANTY_ISS_DTL          IN    LBL_WORKORDEREXT.WARRANTY_ISS_DTL%TYPE,
    I_ESTIMATE_REQD             IN    LBL_WORKORDEREXT.ESTIMATE_REQD%TYPE,
    I_SAFETY_ISSUE              IN    LBL_WORKORDEREXT.SAFETY_ISSUE%TYPE,
    I_HAZARDS                   IN    LBL_WORKORDEREXT.HAZARDS%TYPE,
    I_HAZARDS_DTL               IN    LBL_WORKORDEREXT.HAZARDS_DTL%TYPE,
    I_FOLLOW_STOP_WO            IN    LBL_WORKORDEREXT.FOLLOW_STOP_WO%TYPE,
    I_FOLLOW_STOP_WONUM         IN    LBL_WORKORDEREXT.FOLLOW_STOP_WONUM%TYPE,
    I_FOLLOW_STOP_DTL           IN    LBL_WORKORDEREXT.FOLLOW_STOP_DTL%TYPE,
    I_SELF_WO                   IN    LBL_WORKORDEREXT.SELF_WO%TYPE,
    I_EST_HRS                   IN    LBL_WORKORDEREXT.EST_HRS%TYPE,
    I_PARENT_WO_EXISTS          IN    LBL_WORKORDEREXT.PARENT_WO_EXISTS%TYPE,
    I_PARENT_WONUM              IN    LBL_WORKORDEREXT.PARENT_WONUM%TYPE,
    I_WORKREQ_TYPE              IN    LBL_WORKORDEREXT.WORKREQ_TYPE%TYPE,
    I_CHANGEBY                  IN    LBL_WORKORDEREXT.CHANGEBY%TYPE,
    I_REPORTEDBY_MOBILE         IN    LBL_WORKORDEREXT.REPORTEDBY_MOBILE%TYPE,
    I_WO1_MOBILE                IN    LBL_WORKORDEREXT.wo1_mobile%TYPE
  )
 RETURN MAXIMO.WORKORDER.WONUM%TYPE;


FUNCTION INSERT_TRANSP_WORKREQ(
  WORKREQ_TYPE_I     IN BATCH_MAXIMO.LBL_WORKREQ.WORKREQ_TYPE%TYPE,
  REPORTEDBY_I       IN BATCH_MAXIMO.LBL_WORKREQ.REPORTEDBY%TYPE,
  PHONE_I            IN BATCH_MAXIMO.LBL_WORKREQ.PHONE%TYPE,
  WO1_I              IN BATCH_MAXIMO.LBL_WORKREQ.WO1%TYPE,
  BUILDING_I         IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  ROOM_I             IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  FROM_BUILDING_I    IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  FROM_ROOM_I        IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  TO_BUILDING_I      IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  TO_ROOM_I          IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  LOCATION_NOTES_I   IN BATCH_MAXIMO.LBL_WORKREQ.LOCATION_NOTES%TYPE,
  NUMBER_OF_ITEMS_I  IN BATCH_MAXIMO.LBL_WORKREQ.NUMBER_OF_ITEMS%TYPE,
  TYPE_OF_ITEM_I     IN BATCH_MAXIMO.LBL_WORKREQ.TYPE_OF_ITEM%TYPE,
  ITEM_WEIGHT_I      IN BATCH_MAXIMO.LBL_WORKREQ.ITEM_WEIGHT%TYPE,
  RECYCLE_PICKUP_I   IN BATCH_MAXIMO.LBL_WORKREQ.RECYCLE_PICKUP%TYPE,
  HAZARDS_I          IN BATCH_MAXIMO.LBL_WORKREQ.HAZARDS%TYPE,
  GLACCOUNT_I        IN BATCH_MAXIMO.LBL_WORKREQ.GLACCOUNT%TYPE,
  DESCRIPTION_I      IN BATCH_MAXIMO.LBL_WORKREQ.DESCRIPTION%TYPE,
  COMMENTS_I         IN VARCHAR2,
  TARGCOMPDATE_I     IN VARCHAR2, -- MM/DD/YYYY
  CLEANUP_I          IN BATCH_MAXIMO.LBL_WORKREQ.CLEANUP%TYPE,
  CHANGEBY_I         IN BATCH_MAXIMO.LBL_WORKREQ.CHANGEBY%TYPE)
 RETURN MAXIMO.WORKORDER.WONUM%TYPE;

--*****************************************************************************
--  FUNCTION TO INSERT PEOPLE MOVE WORK REQUEST TO THE WORKORDER RELATED TABLES.
--  AFTER SUCCESSFUL INSERT, IT RETURNS WORK ORDER NUMBER
--****************************************************************************
FUNCTION INSERT_PEOPLE_WORKREQ(
  WORKREQ_TYPE_I     IN BATCH_MAXIMO.LBL_WORKREQ.WORKREQ_TYPE%TYPE,
  REPORTEDBY_I       IN BATCH_MAXIMO.LBL_WORKREQ.REPORTEDBY%TYPE,
  PHONE_I            IN BATCH_MAXIMO.LBL_WORKREQ.PHONE%TYPE,
  WO1_I              IN BATCH_MAXIMO.LBL_WORKREQ.WO1%TYPE,
  BUILDING_I         IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  ROOM_I             IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  TO_BUILDING_I      IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  TO_ROOM_I          IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  LOCATION_NOTES_I   IN BATCH_MAXIMO.LBL_WORKREQ.LOCATION_NOTES%TYPE,
  HAZARDS_I          IN BATCH_MAXIMO.LBL_WORKREQ.HAZARDS%TYPE,
  GLACCOUNT_I        IN BATCH_MAXIMO.LBL_WORKREQ.GLACCOUNT%TYPE,
  DESCRIPTION_I      IN BATCH_MAXIMO.LBL_WORKREQ.DESCRIPTION%TYPE,
  COMMENTS_I         IN VARCHAR2,
  TARGCOMPDATE_I     IN VARCHAR2, -- MM/DD/YYYY
  CHANGEBY_I         IN BATCH_MAXIMO.LBL_WORKREQ.CHANGEBY%TYPE)
RETURN MAXIMO.WORKORDER.WONUM%TYPE;


--****************************************************************************
--* FUNCTION TO INSERT CONF ROOM SETUP REQUEST TO THE WORKORDER RELATED TABLES.
--  AFTER SUCCESSFUL INSERT, IT RETURNS WORK ORDER NUMBER
--***************************************************************************
FUNCTION INSERT_CONF_WORKREQ(
  WORKREQ_TYPE_I     IN BATCH_MAXIMO.LBL_WORKREQ.WORKREQ_TYPE%TYPE,
  REPORTEDBY_I       IN BATCH_MAXIMO.LBL_WORKREQ.REPORTEDBY%TYPE,
  PHONE_I            IN BATCH_MAXIMO.LBL_WORKREQ.PHONE%TYPE,
  WO1_I              IN BATCH_MAXIMO.LBL_WORKREQ.WO1%TYPE,
  BUILDING_I         IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  ROOM_I             IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  GLACCOUNT_I        IN BATCH_MAXIMO.LBL_WORKREQ.GLACCOUNT%TYPE,
  DESCRIPTION_I      IN BATCH_MAXIMO.LBL_WORKREQ.DESCRIPTION%TYPE,
  COMMENTS_I         IN VARCHAR2,
  TARGSTARTDATE_I    IN VARCHAR2, -- MM/DD/YYYY
  TARGSTARTTIME_I    IN VARCHAR2,
  TARGCOMPDATE_I     IN VARCHAR2, -- MM/DD/YYYY
  TARGCOMPTIME_I     IN VARCHAR2,
  CONF_BUILDING_I    IN BATCH_MAXIMO.LBL_WORKREQ.CONF_BUILDING%TYPE,
  CONF_ROOM_NUMBER_I IN BATCH_MAXIMO.LBL_WORKREQ.CONF_ROOM_NUMBER%TYPE,
  NUMBER_OF_TABLES_I IN BATCH_MAXIMO.LBL_WORKREQ.NUMBER_OF_TABLES%TYPE,
  NUMBER_OF_CHAIRS_I IN BATCH_MAXIMO.LBL_WORKREQ.NUMBER_OF_CHAIRS%TYPE,
  CONF_ROOM_OPTION_I IN BATCH_MAXIMO.LBL_WORKREQ.CONF_ROOM_OPTION%TYPE,
  TABLES_CHAIRS_REQD_I IN BATCH_MAXIMO.LBL_WORKREQ.TABLES_CHAIRS_REQD%TYPE,
  CHANGEBY_I         IN BATCH_MAXIMO.LBL_WORKREQ.CHANGEBY%TYPE)
RETURN MAXIMO.WORKORDER.WONUM%TYPE;



FUNCTION INSERT_CUSTD_WORKREQ(
  WORKREQ_TYPE_I     IN BATCH_MAXIMO.LBL_WORKREQ.WORKREQ_TYPE%TYPE,
  REPORTEDBY_I       IN BATCH_MAXIMO.LBL_WORKREQ.REPORTEDBY%TYPE,
  PHONE_I            IN BATCH_MAXIMO.LBL_WORKREQ.PHONE%TYPE,
  WO1_I              IN BATCH_MAXIMO.LBL_WORKREQ.WO1%TYPE,
  BUILDING_I         IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  ROOM_I             IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  LOCATION_NOTES_I   IN BATCH_MAXIMO.LBL_WORKREQ.LOCATION_NOTES%TYPE,
  ROUTINE_CUSTODIAL_I   IN BATCH_MAXIMO.LBL_WORKREQ.ROUTINE_CUSTODIAL%TYPE,
  GLACCOUNT_I        IN BATCH_MAXIMO.LBL_WORKREQ.GLACCOUNT%TYPE,
  DESCRIPTION_I      IN BATCH_MAXIMO.LBL_WORKREQ.DESCRIPTION%TYPE,
  COMMENTS_I         IN VARCHAR2,
  TARGCOMPDATE_I     IN VARCHAR2, -- MM/DD/YYYY
  CHANGEBY_I         IN BATCH_MAXIMO.LBL_WORKREQ.CHANGEBY%TYPE)
 RETURN MAXIMO.WORKORDER.WONUM%TYPE;


 FUNCTION UPDATE_GEN_WORKREQ(
    I_MODE                            IN VARCHAR2,
    I_WONUM                     IN MAXIMO.WORKORDER.WONUM%TYPE,
    I_REPORTEDBY                IN    WORKORDER.REPORTEDBY%TYPE,
    I_PHONE                     IN    WORKORDER.PHONE%TYPE,
    I_WO1                       IN    WORKORDER.WO1%TYPE,
    I_WO1_PHONE                 IN    LBL_WORKORDEREXT.WO1_PHONE%TYPE,
    I_BUILDING                  IN    LBL_WORKORDEREXT.BUILDING%TYPE,
    I_ROOM                      IN    LBL_WORKORDEREXT.ROOM%TYPE,
    I_LOCATION_NOTES            IN    LBL_WORKORDEREXT.LOCATION_NOTES%TYPE,
    I_FIRST_AVL_DATETIME        IN    LBL_WORKORDEREXT.FIRST_AVL_DATETIME%TYPE,
    I_TARGSTARTDATE             IN    VARCHAR2, --LBL_WORKORDEREXT.TARGSTARTDATE%TYPE, MM/DD/YYYY
    I_TARGCOMPDATE              IN    VARCHAR2, --LBL_WORKORDEREXT.TARGCOMPDATE%TYPE, MM/DD/YYYY
    I_SCHED_ISSUES              IN    LBL_WORKORDEREXT.SCHED_ISSUES%TYPE,
    I_SCHED_ISSUES_DTL          IN    LBL_WORKORDEREXT.SCHED_ISSUES_DTL%TYPE,
    I_BUILDING_MAINT            IN    LBL_WORKORDEREXT.BUILDING_MAINT%TYPE,
    I_GLACCOUNT                 IN    WORKORDER.GLACCOUNT%TYPE,
    I_DESCRIPTION               IN    WORKORDER.DESCRIPTION%TYPE,
    I_ACCOMP_COND_PROB          IN    LBL_WORKORDEREXT.ACCOMP_COND_PROB%TYPE,
    I_COMMODITYGROUP            IN    WORKORDER.COMMODITYGROUP%TYPE,
    I_COMMODITY                 IN    WORKORDER.COMMODITY%TYPE,
    I_PRIOR_WO                  IN    LBL_WORKORDEREXT.PRIOR_WO%TYPE,
    I_PRIOR_WONUM               IN    LBL_WORKORDEREXT.PRIOR_WONUM%TYPE,
    I_ASSET_DESC                IN    LBL_WORKORDEREXT.ASSET_DESC%TYPE,
    I_WARRANTY_ISSUE            IN    LBL_WORKORDEREXT.WARRANTY_ISSUE%TYPE,
    I_WARRANTY_ISS_DTL          IN    LBL_WORKORDEREXT.WARRANTY_ISS_DTL%TYPE,
    I_ESTIMATE_REQD             IN    LBL_WORKORDEREXT.ESTIMATE_REQD%TYPE,
    I_SAFETY_ISSUE              IN    LBL_WORKORDEREXT.SAFETY_ISSUE%TYPE,
    I_HAZARDS                   IN    LBL_WORKORDEREXT.HAZARDS%TYPE,
    I_HAZARDS_DTL               IN    LBL_WORKORDEREXT.HAZARDS_DTL%TYPE,
    I_FOLLOW_STOP_WO            IN    LBL_WORKORDEREXT.FOLLOW_STOP_WO%TYPE,
    I_FOLLOW_STOP_WONUM         IN    LBL_WORKORDEREXT.FOLLOW_STOP_WONUM%TYPE,
    I_FOLLOW_STOP_DTL           IN    LBL_WORKORDEREXT.FOLLOW_STOP_DTL%TYPE,
    I_SELF_WO                   IN    LBL_WORKORDEREXT.SELF_WO%TYPE,
    I_EST_HRS                   IN    LBL_WORKORDEREXT.EST_HRS%TYPE,
    I_PARENT_WO_EXISTS          IN    LBL_WORKORDEREXT.PARENT_WO_EXISTS%TYPE,
    I_PARENT_WONUM              IN    LBL_WORKORDEREXT.PARENT_WONUM%TYPE,
    I_WORKREQ_TYPE              IN    LBL_WORKORDEREXT.WORKREQ_TYPE%TYPE,
    I_CHANGEBY                  IN    LBL_WORKORDEREXT.CHANGEBY%TYPE,
    I_REPORTEDBY_MOBILE         IN    LBL_WORKORDEREXT.REPORTEDBY_MOBILE%TYPE,
    I_WO1_MOBILE                IN    LBL_WORKORDEREXT.wo1_mobile%TYPE)
 RETURN MAXIMO.WORKORDER.WONUM%TYPE;



FUNCTION UPDATE_CUSTD_WORKREQ(
  MODE_I             IN VARCHAR2,
  WONUM_I            IN MAXIMO.WORKORDER.WONUM%TYPE,
  REPORTEDBY_I       IN BATCH_MAXIMO.LBL_WORKREQ.REPORTEDBY%TYPE,
  PHONE_I            IN BATCH_MAXIMO.LBL_WORKREQ.PHONE%TYPE,
  WO1_I              IN BATCH_MAXIMO.LBL_WORKREQ.WO1%TYPE,
  BUILDING_I         IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  ROOM_I             IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  LOCATION_NOTES_I   IN BATCH_MAXIMO.LBL_WORKREQ.LOCATION_NOTES%TYPE,
  ROUTINE_CUSTODIAL_I   IN BATCH_MAXIMO.LBL_WORKREQ.ROUTINE_CUSTODIAL%TYPE,
  GLACCOUNT_I        IN BATCH_MAXIMO.LBL_WORKREQ.GLACCOUNT%TYPE,
  DESCRIPTION_I      IN BATCH_MAXIMO.LBL_WORKREQ.DESCRIPTION%TYPE,
  COMMENTS_I         IN VARCHAR2,
  TARGCOMPDATE_I     IN VARCHAR2,
  CHANGEBY_I         IN BATCH_MAXIMO.LBL_WORKREQ.CHANGEBY%TYPE)
 RETURN MAXIMO.WORKORDER.WONUM%TYPE;

--****************************************************************************
--* FUNCTION TO UDATE PEOPLE MOVE WORK REQUEST TO THE WORKORDER RELATED TABLES.
--  AFTER SUCCESSFUL INSERT, IT RETURNS WORK ORDER NUMBER
--****************************************************************************
FUNCTION UPDATE_PEOPLE_WORKREQ(
  MODE_I             IN VARCHAR2,
  WONUM_I            IN MAXIMO.WORKORDER.WONUM%TYPE,
  REPORTEDBY_I       IN BATCH_MAXIMO.LBL_WORKREQ.REPORTEDBY%TYPE,
  PHONE_I            IN BATCH_MAXIMO.LBL_WORKREQ.PHONE%TYPE,
  WO1_I              IN BATCH_MAXIMO.LBL_WORKREQ.WO1%TYPE,
  BUILDING_I         IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  ROOM_I             IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  TO_BUILDING_I      IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  TO_ROOM_I          IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  LOCATION_NOTES_I   IN BATCH_MAXIMO.LBL_WORKREQ.LOCATION_NOTES%TYPE,
  HAZARDS_I          IN BATCH_MAXIMO.LBL_WORKREQ.HAZARDS%TYPE,
  GLACCOUNT_I        IN BATCH_MAXIMO.LBL_WORKREQ.GLACCOUNT%TYPE,
  DESCRIPTION_I      IN BATCH_MAXIMO.LBL_WORKREQ.DESCRIPTION%TYPE,
  COMMENTS_I         IN VARCHAR2,
  TARGCOMPDATE_I     IN VARCHAR2,
  CHANGEBY_I         IN BATCH_MAXIMO.LBL_WORKREQ.CHANGEBY%TYPE)
RETURN MAXIMO.WORKORDER.WONUM%TYPE;

--****************************************************************************
-- FUNCTION TO UPDATE CONF ROOM WORK REQUEST TO THE WORKORDER RELATED TABLES.
--  AFTER SUCCESSFUL INSERT, IT RETURNS WORK ORDER NUMBER
--****************************************************************************
FUNCTION UPDATE_CONF_WORKREQ(
  MODE_I             IN VARCHAR2,
  WONUM_I            IN MAXIMO.WORKORDER.WONUM%TYPE,
  REPORTEDBY_I       IN BATCH_MAXIMO.LBL_WORKREQ.REPORTEDBY%TYPE,
  PHONE_I            IN BATCH_MAXIMO.LBL_WORKREQ.PHONE%TYPE,
  WO1_I              IN BATCH_MAXIMO.LBL_WORKREQ.WO1%TYPE,
  BUILDING_I         IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  ROOM_I             IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  GLACCOUNT_I        IN BATCH_MAXIMO.LBL_WORKREQ.GLACCOUNT%TYPE,
  DESCRIPTION_I      IN BATCH_MAXIMO.LBL_WORKREQ.DESCRIPTION%TYPE,
  COMMENTS_I         IN VARCHAR2,
  TARGSTARTDATE_I    IN VARCHAR2,
  TARGSTARTTIME_I    IN VARCHAR2,
  TARGCOMPDATE_I     IN VARCHAR2,
  TARGCOMPTIME_I     IN VARCHAR2,
  CONF_BUILDING_I    IN BATCH_MAXIMO.LBL_WORKREQ.CONF_BUILDING%TYPE,
  CONF_ROOM_NUMBER_I IN BATCH_MAXIMO.LBL_WORKREQ.CONF_ROOM_NUMBER%TYPE,
  NUMBER_OF_TABLES_I  IN BATCH_MAXIMO.LBL_WORKREQ.NUMBER_OF_TABLES%TYPE,
  NUMBER_OF_CHAIRS_I IN BATCH_MAXIMO.LBL_WORKREQ.NUMBER_OF_CHAIRS%TYPE,
  CONF_ROOM_OPTION_I IN BATCH_MAXIMO.LBL_WORKREQ.CONF_ROOM_OPTION%TYPE,
  TABLES_CHAIRS_REQD_I IN BATCH_MAXIMO.LBL_WORKREQ.TABLES_CHAIRS_REQD%TYPE,
  CHANGEBY_I         IN BATCH_MAXIMO.LBL_WORKREQ.CHANGEBY%TYPE)
RETURN MAXIMO.WORKORDER.WONUM%TYPE;


--****************************************************************************
--* FUNCTION TO UPDATE TRANSPORTATION WORK REQUEST TO THE WORKORDER RELATED TABLES.
--  AFTER SUCCESSFUL INSERT, IT RETURNS WORK ORDER NUMBER
--****************************************************************************
FUNCTION UPDATE_TRANSP_WORKREQ(
  MODE_I             IN VARCHAR2,
  WONUM_I            IN MAXIMO.WORKORDER.WONUM%TYPE,
  REPORTEDBY_I       IN BATCH_MAXIMO.LBL_WORKREQ.REPORTEDBY%TYPE,
  PHONE_I            IN BATCH_MAXIMO.LBL_WORKREQ.PHONE%TYPE,
  WO1_I              IN BATCH_MAXIMO.LBL_WORKREQ.WO1%TYPE,
  BUILDING_I         IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  ROOM_I             IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  FROM_BUILDING_I    IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  FROM_ROOM_I        IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  TO_BUILDING_I      IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  TO_ROOM_I          IN MAXIMO.LOCATIONS.LOCATION%TYPE,
  LOCATION_NOTES_I   IN BATCH_MAXIMO.LBL_WORKREQ.LOCATION_NOTES%TYPE,
  NUMBER_OF_ITEMS_I  IN BATCH_MAXIMO.LBL_WORKREQ.NUMBER_OF_ITEMS%TYPE,
  TYPE_OF_ITEM_I     IN BATCH_MAXIMO.LBL_WORKREQ.TYPE_OF_ITEM%TYPE,
  ITEM_WEIGHT_I      IN BATCH_MAXIMO.LBL_WORKREQ.ITEM_WEIGHT%TYPE,
  RECYCLE_PICKUP_I   IN BATCH_MAXIMO.LBL_WORKREQ.RECYCLE_PICKUP%TYPE,
  HAZARDS_I          IN BATCH_MAXIMO.LBL_WORKREQ.HAZARDS%TYPE,
  GLACCOUNT_I        IN BATCH_MAXIMO.LBL_WORKREQ.GLACCOUNT%TYPE,
  DESCRIPTION_I      IN BATCH_MAXIMO.LBL_WORKREQ.DESCRIPTION%TYPE,
  COMMENTS_I         IN VARCHAR2,
  TARGCOMPDATE_I     IN VARCHAR2,
  CLEANUP_I          IN BATCH_MAXIMO.LBL_WORKREQ.CLEANUP%TYPE,
  CHANGEBY_I         IN BATCH_MAXIMO.LBL_WORKREQ.CHANGEBY%TYPE)
 RETURN MAXIMO.WORKORDER.WONUM%TYPE;


--********************************************
-- FUNCTION TO INSERT ESTIMATING WORK REQUEST
--********************************************
FUNCTION INSERT_EST_WORKREQ(
    I_REPORTEDBY                IN    WORKORDER.REPORTEDBY%TYPE,
    I_PHONE                     IN    WORKORDER.PHONE%TYPE,
    I_WO1                       IN    WORKORDER.WO1%TYPE, -- POINT OF CONTACT
    I_WO1_PHONE                 IN    LBL_WORKORDEREXT.WO1_PHONE%TYPE, -- POC PHONE
    I_BUILDING                  IN    LBL_WORKORDEREXT.BUILDING%TYPE,
    I_ROOM                      IN    LBL_WORKORDEREXT.ROOM%TYPE,
    I_LOCATION_NOTES            IN    LBL_WORKORDEREXT.LOCATION_NOTES%TYPE,
    I_TARGSTARTDATE             IN    VARCHAR2, --LBL_WORKORDEREXT.TARGSTARTDATE%TYPE, MM/DD/YYYY
    I_TARGCOMPDATE              IN    VARCHAR2, --LBL_WORKORDEREXT.TARGCOMPDATE%TYPE, MM/DD/YYYY
    I_SCHED_ISSUES_DTL          IN    LBL_WORKORDEREXT.SCHED_ISSUES_DTL%TYPE, -- SCHEDULING CONSTRAINTS
    I_GLACCOUNT                 IN    WORKORDER.GLACCOUNT%TYPE,
    I_DESCRIPTION               IN    WORKORDER.DESCRIPTION%TYPE,
    I_ACCOMP_COND_PROB          IN    LBL_WORKORDEREXT.ACCOMP_COND_PROB%TYPE,-- DESC OF WORK TO BE ESTIMATED
    I_COMMODITYGROUP            IN    WORKORDER.COMMODITYGROUP%TYPE,
    I_COMMODITY                 IN    WORKORDER.COMMODITY%TYPE, -- PURPOSE OF ESTIMATE WORK
    I_NEEDESTBYDATE             IN    VARCHAR2, -- ESTIMATE NEEDED BY DATE MM/DD/YYYY
    I_WORKREQ_TYPE              IN    LBL_WORKORDEREXT.WORKREQ_TYPE%TYPE, -- WET
    I_CHANGEBY                  IN    LBL_WORKORDEREXT.CHANGEBY%TYPE,
    I_REPORTEDBY_MOBILE         IN    LBL_WORKORDEREXT.REPORTEDBY_MOBILE%TYPE,
    I_WO1_MOBILE                IN    LBL_WORKORDEREXT.WO1_MOBILE%TYPE,
    I_OTHERSTAKEID              IN    WORKORDER.REPORTEDBY%TYPE,
    I_OTHERSTAKEPHONE           IN    WORKORDER.PHONE%TYPE,
    I_OTHERSTAKEMOBILE          IN    LBL_WORKORDEREXT.WO1_MOBILE%TYPE
  )
 RETURN MAXIMO.WORKORDER.WONUM%TYPE;


--********************************************
-- FUNCTION TO UPDATE  ESTIMATING WORK REQUEST
--********************************************
FUNCTION UPDATE_EST_WORKREQ(
    I_MODE                      IN    VARCHAR2,
    I_WONUM                     IN    MAXIMO.WORKORDER.WONUM%TYPE,
    I_REPORTEDBY                IN    WORKORDER.REPORTEDBY%TYPE,
    I_PHONE                     IN    WORKORDER.PHONE%TYPE,
    I_WO1                       IN    WORKORDER.WO1%TYPE, -- POINT OF CONTACT
    I_WO1_PHONE                 IN    LBL_WORKORDEREXT.WO1_PHONE%TYPE, -- POC PHONE
    I_BUILDING                  IN    LBL_WORKORDEREXT.BUILDING%TYPE,
    I_ROOM                      IN    LBL_WORKORDEREXT.ROOM%TYPE,
    I_LOCATION_NOTES            IN    LBL_WORKORDEREXT.LOCATION_NOTES%TYPE,
    I_TARGSTARTDATE             IN    VARCHAR2, --LBL_WORKORDEREXT.TARGSTARTDATE%TYPE, MM/DD/YYYY
    I_TARGCOMPDATE              IN    VARCHAR2, --LBL_WORKORDEREXT.TARGCOMPDATE%TYPE, MM/DD/YYYY
    I_SCHED_ISSUES_DTL          IN    LBL_WORKORDEREXT.SCHED_ISSUES_DTL%TYPE, -- SCHEDULING CONSTRAINTS
    I_GLACCOUNT                 IN    WORKORDER.GLACCOUNT%TYPE,
    I_DESCRIPTION               IN    WORKORDER.DESCRIPTION%TYPE,
    I_ACCOMP_COND_PROB          IN    LBL_WORKORDEREXT.ACCOMP_COND_PROB%TYPE,-- DESC OF WORK TO BE ESTIMATED
    I_COMMODITYGROUP            IN    WORKORDER.COMMODITYGROUP%TYPE,
    I_COMMODITY                 IN    WORKORDER.COMMODITY%TYPE, -- PURPOSE OF ESTIMATE WORK
    I_NEEDESTBYDATE             IN    VARCHAR2, -- ESTIMATE NEEDED BY DATE MM/DD/YYYY
    I_WORKREQ_TYPE              IN    LBL_WORKORDEREXT.WORKREQ_TYPE%TYPE, -- WET
    I_CHANGEBY                  IN    LBL_WORKORDEREXT.CHANGEBY%TYPE,
    I_REPORTEDBY_MOBILE         IN    LBL_WORKORDEREXT.REPORTEDBY_MOBILE%TYPE,
    I_WO1_MOBILE                IN    LBL_WORKORDEREXT.WO1_MOBILE%TYPE,
    I_OTHERSTAKEID              IN    WORKORDER.REPORTEDBY%TYPE,
    I_OTHERSTAKEPHONE           IN    WORKORDER.PHONE%TYPE,
    I_OTHERSTAKEMOBILE          IN    LBL_WORKORDEREXT.WO1_MOBILE%TYPE

  )
 RETURN MAXIMO.WORKORDER.WONUM%TYPE;



--***************************************************************************
--* FUNCTION TO GET EMPLOYEE DETAILS (NAME, PHONE, EMAIL ETC)
--****************************************************************************
FUNCTION GET_EMPLOYEE_DETAILS(
  PERSONID_I             IN PERSON.personid%TYPE,
  TYPE_I                 IN WORKORDER.DESCRIPTION%TYPE)
  RETURN MAXIMO.WORKORDER.DESCRIPTION%TYPE;



--****************************************************
-- GET FAM INFORMATION AS PER LOCATION AND WORK TYPE
--****************************************************
FUNCTION GET_FAMINFO(LOCATION_I IN WORKORDER.LOCATION%TYPE,
                     WORKTYPE_I IN WORKORDER.WORKTYPE%TYPE)
RETURN MAXIMO.WORKORDER.DESCRIPTION%TYPE;


--*******************************************************************
-- COMMON PROCEDURE TO PREPARE FIELD VALUES (USED IN ADD/MODIFY)
--*******************************************************************
PROCEDURE PREPARE_GENWORK_VALUES
(
    I_REPORTEDBY                IN    WORKORDER.REPORTEDBY%TYPE,
    I_PHONE                     IN    WORKORDER.PHONE%TYPE,
    I_WO1                       IN    WORKORDER.WO1%TYPE,
    I_WO1_PHONE                 IN    LBL_WORKORDEREXT.WO1_PHONE%TYPE,
    I_BUILDING                  IN    LBL_WORKORDEREXT.BUILDING%TYPE,
    I_ROOM                      IN    LBL_WORKORDEREXT.ROOM%TYPE,
    I_LOCATION_NOTES            IN    LBL_WORKORDEREXT.LOCATION_NOTES%TYPE,
    I_FIRST_AVL_DATETIME        IN    LBL_WORKORDEREXT.FIRST_AVL_DATETIME%TYPE,
    I_TARGSTARTDATE             IN    VARCHAR2, --LBL_WORKORDEREXT.TARGSTARTDATE%TYPE,
    I_TARGCOMPDATE              IN    VARCHAR2, --LBL_WORKORDEREXT.TARGCOMPDATE%TYPE,
    I_SCHED_ISSUES              IN    LBL_WORKORDEREXT.SCHED_ISSUES%TYPE,
    I_SCHED_ISSUES_DTL          IN    LBL_WORKORDEREXT.SCHED_ISSUES_DTL%TYPE,
    I_BUILDING_MAINT            IN    LBL_WORKORDEREXT.BUILDING_MAINT%TYPE,
    I_GLACCOUNT                 IN    WORKORDER.GLACCOUNT%TYPE,
    I_DESCRIPTION               IN    WORKORDER.DESCRIPTION%TYPE,
    I_ACCOMP_COND_PROB          IN    LBL_WORKORDEREXT.ACCOMP_COND_PROB%TYPE,
    I_COMMODITYGROUP            IN    WORKORDER.COMMODITYGROUP%TYPE,
    I_COMMODITY                 IN    WORKORDER.COMMODITY%TYPE,
    I_PRIOR_WO                  IN    LBL_WORKORDEREXT.PRIOR_WO%TYPE,
    I_PRIOR_WONUM               IN    LBL_WORKORDEREXT.PRIOR_WONUM%TYPE,
    I_ASSET_DESC                IN    LBL_WORKORDEREXT.ASSET_DESC%TYPE,
    I_WARRANTY_ISSUE            IN    LBL_WORKORDEREXT.WARRANTY_ISSUE%TYPE,
    I_WARRANTY_ISS_DTL          IN    LBL_WORKORDEREXT.WARRANTY_ISS_DTL%TYPE,
    I_ESTIMATE_REQD             IN    LBL_WORKORDEREXT.ESTIMATE_REQD%TYPE,
    I_SAFETY_ISSUE              IN    LBL_WORKORDEREXT.SAFETY_ISSUE%TYPE,
    I_HAZARDS                   IN    LBL_WORKORDEREXT.HAZARDS%TYPE,
    I_HAZARDS_DTL               IN    LBL_WORKORDEREXT.HAZARDS_DTL%TYPE,
    I_FOLLOW_STOP_WO            IN    LBL_WORKORDEREXT.FOLLOW_STOP_WO%TYPE,
    I_FOLLOW_STOP_WONUM         IN    LBL_WORKORDEREXT.FOLLOW_STOP_WONUM%TYPE,
    I_FOLLOW_STOP_DTL           IN    LBL_WORKORDEREXT.FOLLOW_STOP_DTL%TYPE,
    I_SELF_WO                   IN    LBL_WORKORDEREXT.SELF_WO%TYPE,
    I_EST_HRS                   IN    LBL_WORKORDEREXT.EST_HRS%TYPE,
    I_PARENT_WO_EXISTS          IN    LBL_WORKORDEREXT.PARENT_WO_EXISTS%TYPE,
    I_PARENT_WONUM              IN    LBL_WORKORDEREXT.PARENT_WONUM%TYPE,
    LOCATION_T                  OUT   WORKORDER.LOCATION%TYPE,
    TARGSTARTDATE_T             OUT   WORKORDER.TARGSTARTDATE%TYPE,
    TARGCOMPDATE_T              OUT   WORKORDER.TARGCOMPDATE%TYPE,
    T_LBL_RELEASE_STATUS        OUT   WORKORDER.LBL_RELEASE_STATUS%TYPE,
    LDTEXT_T                    OUT   LONGDESCRIPTION.LDTEXT%TYPE,
    CURRENTDATE_T               OUT   WORKORDER.CHANGEDATE%TYPE
  );


END;
