CREATE OR REPLACE PACKAGE BODY LBL_MAXIMO_QUERY AS

        /* FUNCTION THAT GETS THE NUMBER OF CHILDREN WORK ORDERS A WORK ORDER HAS THAT
        HAVE PLANNED MATERIALS */

        FUNCTION NUM_CHILD_WITH_MATERIALS(V_WONUM IN MAXIMO.WORKORDER.WONUM%TYPE)
                        RETURN NUMBER
        IS
                V_NUM_CHILDREN NUMBER := 0;
        BEGIN
                SELECT COUNT(*) INTO V_NUM_CHILDREN
                FROM MAXIMO.WORKORDER
                WHERE MAXIMO.WORKORDER.PARENT=V_WONUM
                AND MAXIMO.WORKORDER.WONUM IN
                (SELECT DISTINCT MAXIMO.WPMATERIAL.WONUM
                FROM MAXIMO.WPMATERIAL);

                RETURN V_NUM_CHILDREN;
        END NUM_CHILD_WITH_MATERIALS;



    FUNCTION GET_MONTHLY_VEHICLE_DETAILS(ASSETNUM_I IN MAXIMO.ASSET.ASSETNUM%TYPE,
    FINANCIALPERIOD_I IN MAXIMO.FINANCIALPERIODS.FINANCIALPERIOD%TYPE,
    TYPE_I  VARCHAR2)
     RETURN NUMBER
   IS
          RETURN_NUMBER_O NUMBER :=0;
          MILEAGE_COST_T  NUMBER :=0;
          FEEDER_COST_T   NUMBER :=0;
          NUMBER_OF_MILES_T NUMBER :=0;
          NUMBER_OF_USAGES_T NUMBER :=0;
   BEGIN

           IF TYPE_I = 'FEEDER_MILES' THEN
             SELECT NVL(SUM(B.INVOICEQTY),0)
             INTO   NUMBER_OF_MILES_T
             FROM MAXIMO.INVOICECOST A, MAXIMO.INVOICELINE B,
             MAXIMO.INVOICE C
             WHERE A.SITEID='FAC'
             AND   A.INVOICENUM=B.INVOICENUM
             AND   A.INVOICELINENUM=B.INVOICELINENUM
             AND   B.SITEID='FAC'
             AND   B.INVOICENUM=C.INVOICENUM
             AND   C.SITEID='FAC'
             AND   C.INVOICENUM LIKE 'FLEET%'
             AND   C.FINANCIALPERIOD=FINANCIALPERIOD_I
             AND   B.INVOICEUNIT='MILES'
             AND   A.ASSETNUM=ASSETNUM_I;

             RETURN_NUMBER_O := NUMBER_OF_MILES_T;
          END IF;

          IF TYPE_I = 'MILEAGE_COST' THEN
             SELECT NVL(SUM(A.LINECOST),0)
             INTO   MILEAGE_COST_T
             FROM MAXIMO.INVOICECOST A, MAXIMO.INVOICELINE B,
             MAXIMO.INVOICE C
             WHERE A.SITEID='FAC'
             AND   A.INVOICENUM=B.INVOICENUM
             AND   A.INVOICELINENUM=B.INVOICELINENUM
             AND   B.SITEID='FAC'
             AND   B.INVOICENUM=C.INVOICENUM
             AND   C.SITEID='FAC'
             AND   C.INVOICENUM LIKE 'FLEET%'
             AND   C.FINANCIALPERIOD=FINANCIALPERIOD_I
             AND   B.INVOICEUNIT='MILES'
             AND   A.ASSETNUM=ASSETNUM_I;

             RETURN_NUMBER_O := MILEAGE_COST_T;
          END IF;

           IF TYPE_I = 'FEEDER_COST' THEN
             SELECT NVL(SUM(A.LINECOST),0)
             INTO   FEEDER_COST_T
             FROM MAXIMO.INVOICECOST A, MAXIMO.INVOICELINE B,
             MAXIMO.INVOICE C
             WHERE A.SITEID='FAC'
             AND   A.INVOICENUM=B.INVOICENUM
             AND   A.INVOICELINENUM=B.INVOICELINENUM
             AND   B.SITEID='FAC'
             AND   B.INVOICENUM=C.INVOICENUM
             AND   C.SITEID='FAC'
             AND   C.INVOICENUM LIKE 'FLEET%'
             AND   C.FINANCIALPERIOD=FINANCIALPERIOD_I
             AND   A.ASSETNUM=ASSETNUM_I;

             RETURN_NUMBER_O := FEEDER_COST_T;
          END IF;

          IF TYPE_I = 'NUMBER_OF_USAGES' THEN
             SELECT NVL(SUM(A.LBL_TRIPS),0)
             INTO   NUMBER_OF_USAGES_T
             FROM MAXIMO.TOOLTRANS A
             WHERE A.ORGID='LBNL'
             AND   A.ITEMNUM='VEHTRIPS'
             AND   A.ASSETNUM=ASSETNUM_I
             AND   A.LBL_STARTDATE >= (SELECT
             B.PERIODSTART FROM MAXIMO.FINANCIALPERIODS B
             WHERE B.FINANCIALPERIOD=FINANCIALPERIOD_I)
             AND  A.LBL_STARTDATE < (SELECT
             C.PERIODEND FROM MAXIMO.FINANCIALPERIODS C
             WHERE C.FINANCIALPERIOD=FINANCIALPERIOD_I);

             RETURN_NUMBER_O := NUMBER_OF_USAGES_T;
          END IF;

         RETURN     RETURN_NUMBER_O;

   END;

FUNCTION IS_VEHICLE_USEABLE(ASSETNUM_I IN MAXIMO.ASSET.ASSETNUM%TYPE,
         FINANCIALPERIOD_I IN MAXIMO.FINANCIALPERIODS.FINANCIALPERIOD%TYPE)
        RETURN VARCHAR2
      IS

      WONUM_T       MAXIMO.WORKORDER.WONUM%TYPE;
      HISTORYFLAG_T MAXIMO.WORKORDER.HISTORYFLAG%TYPE;
      PERIODSTART_T MAXIMO.FINANCIALPERIODS.PERIODSTART%TYPE;
      PERIODEND_T   MAXIMO.FINANCIALPERIODS.PERIODEND%TYPE;
      CHANGEDATE_T  MAXIMO.WOSTATUS.CHANGEDATE%TYPE;
      RETURN_T VARCHAR2(1) :='Y';

      BEGIN

      SELECT WONUM, HISTORYFLAG
      INTO WONUM_T, HISTORYFLAG_T
      FROM MAXIMO.WORKORDER
      WHERE  ORGID='LBNL'
      AND    SITEID='FAC'
      AND    ASSETNUM=ASSETNUM_I
      AND    DESCRIPTION LIKE 'FLEET:VEHICLE TRIPS USAGE%';

      IF HISTORYFLAG_T=0 THEN
        RETURN_T :='Y';
      ELSE
        SELECT MAX(B.CHANGEDATE) INTO CHANGEDATE_T
        FROM MAXIMO.WOSTATUS B
        WHERE B.WONUM=WONUM_T
        AND   B.STATUS IN ('CAN','CLOSE');

        SELECT PERIODSTART, PERIODEND
        INTO PERIODSTART_T, PERIODEND_T
        FROM MAXIMO.FINANCIALPERIODS
        WHERE  FINANCIALPERIOD=FINANCIALPERIOD_I;

        IF CHANGEDATE_T < PERIODSTART_T THEN
           RETURN_T :='N';
        ELSE
           RETURN_T :='Y';
        END IF;
     END IF;

        RETURN  RETURN_T;

      EXCEPTION
        WHEN OTHERS THEN
         RETURN_T := 'N';

       RETURN RETURN_T;

   END;



FUNCTION GET_WORKORDER_DATE(ORGID_I  IN WORKORDER.ORGID%TYPE,
                            SITEID_I IN WORKORDER.ORGID%TYPE,
                            WONUM_I  IN WORKORDER.WONUM%TYPE,
                            TYPE_I   IN WORKORDER.DESCRIPTION%TYPE)
     RETURN DATE

      IS

       DATE_T WORKORDER.CHANGEDATE%TYPE :=NULL;

      BEGIN

       IF (TYPE_I ='APPR') THEN
         BEGIN

          SELECT C.CHANGEDATE
          INTO DATE_T
          FROM   MAXIMO.WOSTATUS C
          WHERE  C.ORGID=ORGID_I
          AND    C.SITEID=SITEID_I
          AND    C.WONUM=WONUM_I
          AND    C.STATUS IN (SELECT E.VALUE FROM MAXIMO.SYNONYMDOMAIN E
                              WHERE E.DOMAINID='WOSTATUS'
                              AND E.MAXVALUE NOT IN ('WAPPR','CAN','CLOSE','HISTEDIT'))
          AND    C.CHANGEDATE=(SELECT MIN(D.CHANGEDATE)
          FROM MAXIMO.WOSTATUS D
          WHERE D.ORGID=C.ORGID
          AND D.SITEID=C.SITEID
          AND D.WONUM=C.WONUM
          AND D.STATUS IN (SELECT F.VALUE FROM MAXIMO.SYNONYMDOMAIN F
                           WHERE F.DOMAINID='WOSTATUS'
                           AND   F.MAXVALUE NOT IN ('WAPPR','CAN','CLOSE','HISTEDIT')));

         EXCEPTION WHEN OTHERS THEN
           NULL;
       END;

      END IF;

      IF (TYPE_I ='INPRG') THEN
         BEGIN

          SELECT C.CHANGEDATE
          INTO DATE_T
          FROM   MAXIMO.WOSTATUS C
          WHERE  C.ORGID=ORGID_I
          AND    C.SITEID=SITEID_I
          AND    C.WONUM=WONUM_I
          AND    C.STATUS IN (SELECT E.VALUE FROM MAXIMO.SYNONYMDOMAIN E
                              WHERE E.DOMAINID='WOSTATUS'
                              AND E.MAXVALUE NOT IN ('WAPPR','APPR','CAN','CLOSE','HISTEDIT'))
          AND    C.CHANGEDATE=(SELECT MIN(D.CHANGEDATE)
          FROM MAXIMO.WOSTATUS D
          WHERE D.ORGID=C.ORGID
          AND D.SITEID=C.SITEID
          AND D.WONUM=C.WONUM
          AND D.STATUS IN (SELECT F.VALUE FROM MAXIMO.SYNONYMDOMAIN F
                           WHERE F.DOMAINID='WOSTATUS'
                           AND   F.MAXVALUE NOT IN ('WAPPR','CAN','APPR','CLOSE','HISTEDIT')));

         EXCEPTION WHEN OTHERS THEN
           NULL;
       END;

      END IF;

       IF (TYPE_I ='COMP') THEN
         BEGIN

          SELECT C.CHANGEDATE
          INTO DATE_T
          FROM   MAXIMO.WOSTATUS C
          WHERE  C.ORGID=ORGID_I
          AND    C.SITEID=SITEID_I
          AND    C.WONUM=WONUM_I
          AND    C.STATUS IN (SELECT E.VALUE FROM MAXIMO.SYNONYMDOMAIN E
                              WHERE E.DOMAINID='WOSTATUS'
                              AND E.MAXVALUE  IN ('COMP','CLOSE'))
          AND    C.CHANGEDATE=(SELECT MIN(D.CHANGEDATE)
          FROM MAXIMO.WOSTATUS D
          WHERE D.ORGID=C.ORGID
          AND D.SITEID=C.SITEID
          AND D.WONUM=C.WONUM
          AND D.STATUS IN (SELECT F.VALUE FROM MAXIMO.SYNONYMDOMAIN F
                           WHERE F.DOMAINID='WOSTATUS'
                           AND   F.MAXVALUE  IN ('COMP','CLOSE')));

         EXCEPTION WHEN OTHERS THEN
           NULL;
       END;

      END IF;





      RETURN DATE_T;



      END;


END LBL_MAXIMO_QUERY;
